### PR TITLE
[FIX] (#66) - fix setting range

### LINKED ISSUE #66: Fix setting range
Fix setting range

### PR DESCRIPTION
**Pull request by dazzel3**
## What?
fix setting range

## Why?
difference of each data's range

## How?
set different range

## Testing?
X

## Screenshots (optional)
X

## Anything Else?
X 

## Reviewers
@gayoungyeom

### CODE REVIEW

File: happyfarmer/src/components/Slider.jsx [hunk 1]
```diff
@@ -21,30 +23,88 @@ const handle = (props) => {
...
-
-const Sliders = ({ range, setRange, rangeVal }) => {
+const Sliders = ({ range, setRange, rangeVal, title }) => {
   const onSliderChange = (val) => {
     const value = { lower: val[0], upper: val[1] };
     setRange(value);
   };
 
+  let marks, min, max;
+  if (title == 'Temperature') {
```
Comment (gayoungyeom) [inline happyfarmer/src/components/Slider.jsx:33]: 일단 머지하고 각자 더 좋은 방식 찾아봅시당

**Review by gayoungyeom — COMMENTED** [review]
리뷰 확인해주세요!

File: happyfarmer/src/components/Slider.jsx (hunk 1 above)
Comment (dazzel3) [reply happyfarmer/src/components/Slider.jsx:33]: 좋습니다~~
